{"Modified":"2022-10-25T19:23:00","Published":"2021-05-27T00:15:00","access":{"authentication":"NONE","complexity":"MEDIUM","vector":"NETWORK"},"assigner":"secalert@redhat.com","capec":[],"cvss":4.3,"cvss-time":"2022-10-25T19:23:00","cvss-vector":"AV:N/AC:M/Au:N/C:N/I:N/A:P","cwe":"CWE-617","id":"CVE-2021-30501","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2022-10-25T19:23:00","references":["https://bugzilla.redhat.com/show_bug.cgi?id=1948696","https://github.com/upx/upx/issues/486","https://github.com/upx/upx/pull/487","https://github.com/upx/upx/commit/28e761cd42211dfe0124b7a29b2f74730f453e46"],"summary":"An assertion abort was found in upx MemBuffer::alloc() in mem.cpp, in version UPX 4.0.0. The flow allows attackers to cause a denial of service (abort) via a crafted file.","vulnerable_configuration":[{"id":"cpe:2.3:a:upx_project:upx:4.0.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:upx_project:upx:4.0.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:redhat:enterprise_linux:7.0:*:*:*:*:*:*:*","title":"cpe:2.3:o:redhat:enterprise_linux:7.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:*:*","title":"cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:upx_project:upx:4.0.0:*:*:*:*:*:*:*","cpe:2.3:o:redhat:enterprise_linux:7.0:*:*:*:*:*:*:*","cpe:2.3:o:fedoraproject:fedora:33:*:*:*:*:*:*:*"]}