{"Modified":"2022-06-15T14:34:00","Published":"2022-06-08T20:15:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":7.5,"cvss-time":"2022-06-15T14:34:00","cvss-vector":"AV:N/AC:L/Au:N/C:P/I:P/A:P","cwe":"NVD-CWE-noinfo","id":"CVE-2022-30882","impact":{"availability":"PARTIAL","confidentiality":"PARTIAL","integrity":"PARTIAL"},"last-modified":"2022-06-15T14:34:00","references":["https://github.com/egeback/pyanxdns/issues/1","https://pypi.org/project/pyanxdns/","http://pypi.doubanio.com/simple/request"],"summary":"pyanxdns package in PyPI version 0.2 is vulnerable to code execution backdoor. The impact is: execute arbitrary code (remote). When installing the pyanxdns package of version 0.2, the request package will be installed.","vulnerable_configuration":[{"id":"cpe:2.3:a:pyanxdns_project:pyanxdns:0.2:*:*:*:*:*:*:*","title":"cpe:2.3:a:pyanxdns_project:pyanxdns:0.2:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:pyanxdns_project:pyanxdns:0.2:*:*:*:*:*:*:*"]}