{"Modified":"2023-03-26T19:15:00","Published":"2023-03-26T19:15:00","access":{},"assigner":"cve@mitre.org","cvss":null,"cwe":"Unknown","id":"CVE-2023-28859","impact":{},"last-modified":"2023-03-26T19:15:00","references":["https://github.com/redis/redis-py/pull/2641","https://github.com/redis/redis-py/issues/2665"],"summary":"redis-py through 4.5.3 leaves a connection open after canceling an async Redis command at an inopportune time (in the case of a non-pipeline operation), and can send response data to the client of an unrelated request. NOTE: this issue exists because of an incomplete fix for CVE-2023-28858.","vulnerable_configuration":[],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":[]}