{"Modified":"2008-09-05T20:37:00","Published":"2004-03-03T05:00:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":5,"cvss-time":"2008-09-05T20:37:00","cvss-vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","cwe":"NVD-CWE-Other","id":"CVE-2004-0096","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2008-09-05T20:37:00","redhat":{"advisories":[{"rhsa":{"id":"RHSA-2004:058"}},{"rhsa":{"id":"RHSA-2004:063"}}],"rpms":["mod_python-0:3.0.3-3.ent","mod_python-debuginfo-0:3.0.3-3.ent"]},"references":["http://security.gentoo.org/glsa/glsa-200401-03.xml","http://www.modpython.org/pipermail/mod_python/2004-January/014879.html","http://www.redhat.com/support/errata/RHSA-2004-058.html","http://www.redhat.com/support/errata/RHSA-2004-063.html"],"refmap":{"gentoo":["GLSA-200401-03"],"mlist":["[mod_python] 20040122 [ANNOUNCE] Mod_python 2.7.10"]},"summary":"Unknown vulnerability in mod_python 2.7.9 allows remote attackers to cause a denial of service (httpd crash) via a certain query string, a variant of CAN-2003-0973.","vulnerable_configuration":[{"id":"cpe:2.3:a:apache:mod_python:2.7.9:*:*:*:*:*:*:*","title":"cpe:2.3:a:apache:mod_python:2.7.9:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:apache:mod_python:2.7.9:*:*:*:*:*:*:*"]}