{"Modified":"2020-08-24T17:37:00","Published":"2019-11-09T02:15:00","access":{"authentication":"SINGLE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":4,"cvss-time":"2020-08-24T17:37:00","cvss-vector":"AV:N/AC:L/Au:S/C:P/I:N/A:N","cwe":"NVD-CWE-noinfo","id":"CVE-2019-4334","impact":{"availability":"NONE","confidentiality":"PARTIAL","integrity":"NONE"},"last-modified":"2020-08-24T17:37:00","references":["https://exchange.xforce.ibmcloud.com/vulnerabilities/161271","https://www.ibm.com/support/pages/node/1074144"],"refmap":{"confirm":["https://www.ibm.com/support/pages/node/1074144"],"xf":["ibm-cognos-cve20194334-info-disc (161271)"]},"summary":"IBM Cognos Analytics 11.0 and 11.1 could reveal sensitive information to an authenticated user that could be used in future attacks against the system. IBM X-Force ID: 161271.","vulnerable_configuration":[{"id":"cpe:2.3:a:ibm:cognos_analytics:11.0.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.0.0:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*","title":"cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:ibm:cognos_analytics:11.0.0:*:*:*:*:*:*:*","cpe:2.3:a:ibm:cognos_analytics:11.1.0:*:*:*:*:*:*:*"]}