{"Modified":"2019-12-17T23:15:00","Published":"2019-11-26T13:15:00","access":{"authentication":"NONE","complexity":"LOW","vector":"NETWORK"},"assigner":"cve@mitre.org","capec":[],"cvss":5,"cvss-time":"2019-12-17T23:15:00","cvss-vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","cwe":"CWE-755","id":"CVE-2019-14853","impact":{"availability":"PARTIAL","confidentiality":"NONE","integrity":"NONE"},"last-modified":"2019-12-17T23:15:00","references":["https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14853","https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3","https://seclists.org/bugtraq/2019/Dec/33","https://www.debian.org/security/2019/dsa-4588"],"refmap":{"bugtraq":["20191218 [SECURITY] [DSA 4588-1] python-ecdsa security update"],"confirm":["https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14853"],"debian":["DSA-4588"],"misc":["https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3"]},"summary":"An error-handling flaw was found in python-ecdsa before version 0.13.3. During signature decoding, malformed DER signatures could raise unexpected exceptions (or no exceptions at all), which could lead to a denial of service.","vulnerable_configuration":[{"id":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.5:*:*:*:*:*:*:*","title":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.5:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.6:*:*:*:*:*:*:*","title":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.6:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.7:*:*:*:*:*:*:*","title":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.7:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.8:*:*:*:*:*:*:*","title":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.8:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.9:*:*:*:*:*:*:*","title":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.9:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.10:*:*:*:*:*:*:*","title":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.10:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.11:*:*:*:*:*:*:*","title":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.11:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.12:*:*:*:*:*:*:*","title":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.12:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.13:*:*:*:*:*:*:*","title":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.13:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.13.1:*:*:*:*:*:*:*","title":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.13.1:*:*:*:*:*:*:*"},{"id":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.13.2:*:*:*:*:*:*:*","title":"cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.13.2:*:*:*:*:*:*:*"}],"vulnerable_configuration_cpe_2_2":[],"vulnerable_product":["cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.5:*:*:*:*:*:*:*","cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.6:*:*:*:*:*:*:*","cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.7:*:*:*:*:*:*:*","cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.8:*:*:*:*:*:*:*","cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.9:*:*:*:*:*:*:*","cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.10:*:*:*:*:*:*:*","cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.11:*:*:*:*:*:*:*","cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.12:*:*:*:*:*:*:*","cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.13:*:*:*:*:*:*:*","cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.13.1:*:*:*:*:*:*:*","cpe:2.3:a:python-ecdsa_project:python-ecdsa:0.13.2:*:*:*:*:*:*:*"]}